### ISSUE TITLE
Bootstrap theme does not work with bootstrap@4.2.1

### ISSUE THREAD

**Issue by altso** [telerik/kendo-themes#520]
## Current behavior

`@progress/kendo-theme-bootstrap@2.17.1` does not work along with `bootstrap@4.2.1`. I get a compilation error:
```
> ng build

Date: 2018-12-28T18:29:52.304Z
Hash: 55b11cdf650097cd5ced
Time: 43559ms
chunk {main} main.js, main.js.map (main) 8.53 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 223 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 16.4 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.11 MB [initial] [rendered]

ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

undefined
           ^
      Argument `$color` of `rgba($color, $alpha)` must be a color
      in C:\Temp\ankenboot\node_modules\@progress\kendo-theme-bootstrap\scss\menu\_theme.scss (line 2, column 13)
```

## Expected behavior
`ng build` completes successfully without any errors

## Minimal reproduction of the problem with instructions
Please see repo here: https://github.com/altso/ankenboot

## What is the motivation or use case for changing the behavior?
To have an ability to stay on the latest version of bootstrap.

## Environment
Product:
* Kendo Ui for Angular

Package versions:
```
+-- @angular-devkit/build-angular@0.11.4
+-- @angular/animations@7.1.4
+-- @angular/cli@7.1.4
+-- @angular/common@7.1.4
+-- @angular/compiler@7.1.4
+-- @angular/compiler-cli@7.1.4
+-- @angular/core@7.1.4
+-- @angular/forms@7.1.4
+-- @angular/language-service@7.1.4
+-- @angular/platform-browser@7.1.4
+-- @angular/platform-browser-dynamic@7.1.4
+-- @angular/router@7.1.4
+-- @progress/kendo-theme-bootstrap@2.17.1
+-- @types/jasmine@2.8.14
+-- @types/jasminewd2@2.0.6
+-- @types/node@8.9.5
+-- bootstrap@4.2.1
+-- codelyzer@4.5.0
+-- core-js@2.6.1
+-- jasmine-core@2.99.1
+-- jasmine-spec-reporter@4.2.1
+-- jquery@3.3.1
+-- karma@3.1.4
+-- karma-chrome-launcher@2.2.0
+-- karma-coverage-istanbul-reporter@2.0.4
+-- karma-jasmine@1.1.2
+-- karma-jasmine-html-reporter@0.2.2
+-- popper.js@1.14.6
+-- protractor@5.4.2
+-- rxjs@6.3.3
+-- ts-node@7.0.1
+-- tslib@1.9.3
+-- tslint@5.11.0
+-- typescript@3.1.6
`-- zone.js@0.8.26
```

Browser:
N/A

System:
- TypeScript version: 2.7.2
- Node version: v10.13.0 (6.5.0)
- Platform:  Windows

The same code works just fine with `bootstrap@4.1.3`

**Comment by merobal** [comment]
This is the error message with `"@progress/kendo-theme-bootstrap": "3.0.0"` and `"bootstrap": "4.2.1"` (latest Angular stack) on `ng serve`:
```
$menu-text: rgba( $header-text, .5 ) !default;
           ^
      Argument `$color` of `rgba($color, $alpha)` must be a color
      in /mnt/c/Github/[project_name]/node_modules/@progress/kendo-theme-bootstrap/scss/menu/_theme.scss (line 2, column 13)
```
_(And works good with `"bootstrap": "4.1.3"`)_

**Comment by merobal** [comment]
It's still an issue with `"@progress/kendo-theme-bootstrap": "3.1.0"`, same error message.

**Comment by merobal** [comment]
This issue is introduced by https://github.com/twbs/bootstrap/pull/27681 via this line: https://github.com/twbs/bootstrap/pull/27681/commits/303121f6c1ac710105abba4b59b47f21823ed328#diff-d8ee409a461718bfb6240710c8c73382R798

**Comment by joneff** [comment]
fixed by twbs/bootstrap@5adcfe97f04a5c2f0b2d0712a6f2332c0bbd8446. Note: you don't need to update kendo-theme-bootstrap. Just bootstrap.
